### PR TITLE
Arch linux install info

### PR DESCRIPTION
**Pull request by ceres-c**
I've uploaded to the AUR a package for this project, so it can be easily sourced and updated from there

### CODE REVIEW

**Comment by florentbr** [comment]
Sorry, but I won't get involved in publishing a proprietary software under trademark/copyright on a public official repository.
I also noticed that you changed the id from `owon-vds-tiny` to `owon-vds`. Be aware that there are different software for the different VDS devices (VDS-1022, VDS-3104, ...).

**Comment by ceres-c** [comment]
You're right about the naming, sorry, I'll change it tomorrow. Regarding the "official" repository, I'd like to point out that the AUR is as official as this repo could possibly be. From the footer on every page 

> AUR packages are user produced content. Any use of the provided files is at your own risk.

**Comment by florentbr** [comment]
Github repositories are attached to individuals or organizations. In this case it's my own repository and it clearly states that it's not the official app. AUR packages just mention a maintainer. It could mislead a user into believing that it's the official OWON application. This is a proprietary software owned by OWON. I'm already breaking the rules by providing modified binaries. I won't get involved any further in this matter. If you are willing to take the risk and face all the legal consequences, feel free to publish a package linked to your own repository.

**Comment by ceres-c** [comment]
AUR package deleted, I'll create a new one with the right name and linked to my own repository with due credit.
I still don't see any difference between hosting it here and packaging the file in a useful, **community-driven** repository. It's simply a matter of comfort, but I don't want to force you.


Also, I'd love to have a talk about legal consequences of my action with a company clearly going against libraries licenses (as they don't embed licenses with their software) and whose [404 page](http://www.owon.com.hk/owontv) is clearly a ripoff of [GitHub's ](https://github.com/404).

**Comment by florentbr** [comment]
The AUR repository contains only software with open source code. The OWON app is proprietary with closed sources. See the difference? I do get your reason and I would fully support it if the source code was provided by OWON under a compatible license. I don't give a shit about OWON given the time I spent fixing their app but I do care about the Linux community and I'm not willing to pollute the repository, nor break the terms of usage.

**Comment by ceres-c** [comment]
It is entirely false that the AUR contains only open source software.
You can simply go to the [package browser](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=&outdated=&SB=p&SO=d&PP=50&do_Search=Go), sort packages by popularity, and you'll see that many of the most popular ones are simply repacked closed source apps. Just to give some examples: `spotify`, `google-chrome`, `skype`, IDEA suite tools and their derivative `android-studio`, `teamviewer`, various `nvidia-` drivers, `dropbox` and many many others.
None of these packages are maintained by any of the owners of the original code, but redistributed under their license. This is indeed the issue in this case, given that owon did not allow us (you, in particular) to modify their software, but I personally think they couldn't care less, given that your repo is still up here.

In light of these considerations I thought it would simply be more comfortable to have this project in the AUR, given there currently are many alike.

**Comment by florentbr** [comment]
My bad, looks like you are right. I can't find the terms and conditions, only a guideline. Still, it doesn't feel right. I wouldn't dare to publish a modified version of Spotify or Skype on AUR.

**Pull request closed without merging**
